language: node_js
cache: yarn

node_js:
- "8"
- "10"
- "12"

jobs:
  include:
    - stage: lint
      script: yarn lint
      node_js: "12"
    - stage: test
      script: yarn test
    - stage: coverage
      script: yarn coverage
      node_js: "12"
