language: node_js
cache: yarn

script: yarn test
node_js:
  - "8"
  - "lts/*"
  - "node"

jobs:
  include:
    - stage: lint
      script: yarn lint
      node_js: "lts/*"
    - stage: coverage
      script: yarn coverage
      node_js: "lts/*"
